site_name: Squad & Arma Wiki
site_description: Tutorials and references for Squad, ArmA 3, and ArmA Reforger
repo_url: ''

nav:
  - Home: index.md
  - Games:
      - Squad: games/squad/index.md
      - ArmA 3: games/arma3/index.md
      - ArmA Reforger: games/reforger/index.md
  - About: about.md

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: 'blue'
      accent: 'amber'
  font:
    text: 'Inter'
    code: 'Roboto Mono'

extra_css:
  - 'assets/css/theme-vars.css'
  - 'assets/css/custom.css'

plugins:
  - search
  - git-revision-date
  - macros

markdown_extensions:
  - toc:
      permalink: '¶'
